language: android

jdk:
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    # - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    - chmod +x prepare-build.sh
    - ./prepare-build.sh

script: "./gradlew build dependencyUpdates -x fabricGenerateResourcesRelease"
