language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.0
    - android-27

before_install:
  - rvm install 2.2.6
  - gem install dropbox-deployment

script: "./gradlew assembleDebug"

after_success:
  - dropbox-deployment
