language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-google-m2repository

before_install:
  - rvm install 2.2.6
  - gem install dropbox-deployment

script: "./gradlew assembleDebug"

after_success:
  - dropbox-deployment
